# Generated by Django 4.1 on 2022-10-19 13:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='URL tiêu đề')),
                ('description', models.TextField(max_length=300, verbose_name='Mô tả')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forum.category', verbose_name='Thể loại cha')),
            ],
            options={
                'verbose_name': 'Thể loại',
                'verbose_name_plural': 'Thể loại',
                'db_table': 'app_categories',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='URL')),
                ('short_description', models.TextField(max_length=300, verbose_name='Mô tả ngắn gọn')),
                ('full_description', models.TextField(verbose_name='Mô tả đầy đủ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Thời gian cập nhật')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='Lý do cập nhật')),
                ('is_fixed', models.BooleanField(db_index=True, default=False, verbose_name='Đã sửa ?')),
                ('is_published', models.BooleanField(default=True, verbose_name='Đăng ?')),
                ('thumbnail', models.ImageField(blank=True, upload_to='images/thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Thumbnail')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_author', to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='forum.category', verbose_name='Thể loại')),
            ],
            options={
                'verbose_name': 'Bài đăng',
                'verbose_name_plural': 'Bài đăng',
                'db_table': 'app_articles',
                'ordering': ('-is_fixed', '-created_at'),
            },
        ),
    ]
