# Generated by Django 4.1 on 2022-10-25 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0005_alter_article_full_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1500, verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày bình luận')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Ngày update')),
                ('is_published', models.BooleanField(default=True, verbose_name='Đăng?')),
                ('is_fixed', models.BooleanField(default=False, verbose_name='Đã sửa?')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='forum.article', verbose_name='Bài đăng')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_author', to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forum.comment', verbose_name='Bình luận cha')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'app_comments',
                'ordering': ('-is_fixed', '-created_at'),
            },
        ),
    ]
